[versions]
accompanist = "0.34.0"
agp = "8.2.0"
android-sdk-compile = "34"
android-sdk-min = "26"
android-sdk-target = "34"
androidx-core = "1.13.1"
androidx-espresso-core = "3.5.1"
androidx-junit = "1.1.5"
androidx-lifecycle-runtime = "2.8.2"
androidx-room = "2.6.1"
compose = "1.6.8"
compose-activity = "1.9.0"
compose-material3 = "1.2.1"
compose-navigation = "2.8.0-beta03"
dagger = "2.51.1"
google-material = "1.12.0"
gson = "2.11.0"
hilt = "1.2.0"
jsoup = "1.17.2"
junit = "4.13.2"
kotlin = "2.0.0"
kotlin-ksp = "2.0.0-1.0.22"
kotlinx-coroutines = "1.8.1"
kotlinx-serialization = "1.7.0"
ktor = "2.3.11"
medzik-android-utils = "1.5.2"
medzik-libcrypto = "1.2.0"
migbase64 = "2.2"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
compose-androidx-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
medzik-android-components = { module = "dev.medzik.android:components", version.ref = "medzik-android-utils" }
medzik-android-crypto = { module = "dev.medzik.android:crypto", version.ref = "medzik-android-utils" }
medzik-android-utils = { module = "dev.medzik.android:utils", version.ref = "medzik-android-utils" }
medzik-libcrypto = { module = "dev.medzik:libcrypto", version.ref = "medzik-libcrypto" }
migbase64 = { module = "com.brsanthu:migbase64", version.ref = "migbase64" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
